# Job to submit a Ray program from a pod outside a running Ray cluster.
apiVersion: batch/v1
kind: Job
metadata:
  name: ray-test-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ray
          image: rayproject/ray:1.4.0-py38
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "wget -O ray-client-test-job.py https://raw.githubusercontent.com/Therealchainman/ray-kubernetes/master/examples/ray-client-test-job.py?token=ALKETSG6A252KVHTTDPRGX3A2W42Q &&
              python ray-client-test-job.py"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi